package cz.zamboch.autopilot.core.physics;

import cz.zamboch.autopilot.core.movement.CandidatePosition;

import java.util.Random;

/**
 * Pre-computed reachable positions at tick+10 from a given initial |velocity|.
 * Stores relative (dx, dy) offsets from the starting position at heading = 0.
 * At runtime: rotate by current heading, translate to current position,
 * clamp to walls, and optionally subsample with jitter to avoid
 * exploitable grid patterns.
 *
 * <p>Tables generated by {@link EnvelopeGenerator} on a 2px grid,
 * embedded in {@link EnvelopeData} as static final arrays (no I/O needed,
 * safe under Robocode's security sandbox).
 *
 * <p>Anti-discretization: candidates are jittered by ±1 px (half the
 * grid spacing) and randomly subsampled. The opponent never sees the
 * same set of evaluation points twice.
 */
public final class ReachableEnvelope {

    /** Horizon (ticks) for which the tables were generated. */
    public static final int HORIZON = 10;

    /** Grid spacing of the pre-computed positions (px). */
    static final int GRID = 2;

    /** Half-grid for random jitter (px). */
    private static final double JITTER = GRID / 2.0;

    /** Robot half-size for wall margin. */
    private static final int MARGIN = RobotPhysics.ROBOT_HALF_SIZE;

    private static final Random RNG = new Random();

    private ReachableEnvelope() {}

    /**
     * Force class loading of envelope tables. Call early (e.g. in robot init)
     * so the static data is ready before the first tick.
     * No-op if already loaded — the JVM guarantees single class init.
     */
    public static void ensureLoaded() {
        // Touching EnvelopeData.ALL triggers its class initializer
        // which allocates the byte[][] from the factory methods.
        // This is a no-op after the first call.
        if (EnvelopeData.ALL == null) {
            throw new IllegalStateException("EnvelopeData failed to load");
        }
    }

    /** Get the interleaved (dx,dy) byte array for the given absolute velocity. */
    private static byte[] getOffsets(int absVelocity) {
        return EnvelopeData.ALL[Math.min(8, Math.max(0, absVelocity))];
    }

    /**
     * Get all candidate positions reachable from the given state at tick+HORIZON.
     * Rotates pre-computed offsets by heading, translates to position,
     * discards positions outside battlefield walls. No jitter applied.
     *
     * @param current starting robot state
     * @param bfW battlefield width
     * @param bfH battlefield height
     * @return array of reachable candidate positions (may be large — ~2000)
     */
    public static CandidatePosition[] getAllCandidates(
            RobotState current, int bfW, int bfH) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);
        int numPoints = data.length / 2;

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        CandidatePosition[] buf = new CandidatePosition[numPoints];
        int n = 0;

        for (int i = 0; i < data.length; i += 2) {
            double dx = data[i];
            double dy = data[i + 1];
            double rx = dx * cosH + dy * sinH;
            double ry = -dx * sinH + dy * cosH;
            double x = current.x + rx;
            double y = current.y + ry;

            if (x < MARGIN || x > bfW - MARGIN
                    || y < MARGIN || y > bfH - MARGIN) {
                continue;
            }
            buf[n++] = new CandidatePosition(x, y, 0.0, HORIZON);
        }

        CandidatePosition[] result = new CandidatePosition[n];
        System.arraycopy(buf, 0, result, 0, n);
        return result;
    }

    /**
     * Zero-allocation subsample: writes into a pre-allocated buffer with jitter.
     * The primary online method for per-tick path planning.
     *
     * @param current starting robot state
     * @param bfW battlefield width
     * @param bfH battlefield height
     * @param buf pre-allocated buffer (each element must be non-null)
     * @param maxCandidates max entries to write into buf
     * @return number of candidates written into buf[0..n-1]
     */
    public static int getCandidatesInto(
            RobotState current, int bfW, int bfH,
            CandidatePosition[] buf, int maxCandidates) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        // Reservoir sampling with jitter — writes into buf, zero allocation
        int seen = 0;

        for (int i = 0; i < data.length; i += 2) {
            double dx = data[i] + (RNG.nextDouble() * 2 - 1) * JITTER;
            double dy = data[i + 1] + (RNG.nextDouble() * 2 - 1) * JITTER;
            double rx = dx * cosH + dy * sinH;
            double ry = -dx * sinH + dy * cosH;
            double x = current.x + rx;
            double y = current.y + ry;

            if (x < MARGIN || x > bfW - MARGIN
                    || y < MARGIN || y > bfH - MARGIN) {
                continue;
            }

            if (seen < maxCandidates) {
                buf[seen].set(x, y, 0.0, HORIZON);
            } else {
                int j = RNG.nextInt(seen + 1);
                if (j < maxCandidates) {
                    buf[j].set(x, y, 0.0, HORIZON);
                }
            }
            seen++;
        }

        return Math.min(seen, maxCandidates);
    }

    /**
     * Count how many envelope positions survive wall clamping.
     * Used to compute ENVELOPE_FILL_RATIO feature.
     *
     * @return [surviving, total] positions
     */
    public static int[] countReachable(RobotState current, int bfW, int bfH) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);
        int numPoints = data.length / 2;

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        int surviving = 0;
        for (int i = 0; i < data.length; i += 2) {
            double rx = data[i] * cosH + data[i + 1] * sinH;
            double ry = -data[i] * sinH + data[i + 1] * cosH;
            double x = current.x + rx;
            double y = current.y + ry;
            if (x >= MARGIN && x <= bfW - MARGIN
                    && y >= MARGIN && y <= bfH - MARGIN) {
                surviving++;
            }
        }
        return new int[]{surviving, numPoints};
    }

    /**
     * Zero-allocation scan of all reachable positions to compute distance range
     * to a target and GF range against a wave. All results written into
     * {@code out[0..3]}: [minDist, maxDist, minGF, maxGF].
     *
     * <p>If no wave is provided (waveOriginX/Y = NaN), GF fields are set to 0.
     *
     * @param current our robot state
     * @param bfW battlefield width
     * @param bfH battlefield height
     * @param targetX opponent X for distance computation
     * @param targetY opponent Y for distance computation
     * @param waveOriginX wave firer's X (NaN to skip GF)
     * @param waveOriginY wave firer's Y
     * @param waveBulletSpeed bullet speed for MEA computation
     * @param fireBearing bearing from wave origin to us at fire time
     * @param out receives [minDist, maxDist, minGF, maxGF, surviving, total]
     */
    public static void scanEnvelope(
            RobotState current, int bfW, int bfH,
            double targetX, double targetY,
            double waveOriginX, double waveOriginY,
            double waveBulletSpeed, double fireBearing,
            double[] out) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        boolean hasWave = !Double.isNaN(waveOriginX);
        double mea = hasWave ? Math.asin(8.0 / waveBulletSpeed) : 1.0;

        double minDist = Double.MAX_VALUE;
        double maxDist = 0;
        double minGF = Double.MAX_VALUE;
        double maxGF = -Double.MAX_VALUE;
        int surviving = 0;

        for (int i = 0; i < data.length; i += 2) {
            double rx = data[i] * cosH + data[i + 1] * sinH;
            double ry = -data[i] * sinH + data[i + 1] * cosH;
            double x = current.x + rx;
            double y = current.y + ry;

            if (x < MARGIN || x > bfW - MARGIN
                    || y < MARGIN || y > bfH - MARGIN) {
                continue;
            }
            surviving++;

            double d = Math.hypot(x - targetX, y - targetY);
            if (d < minDist) minDist = d;
            if (d > maxDist) maxDist = d;

            if (hasWave) {
                double candBearing = Math.atan2(x - waveOriginX, y - waveOriginY);
                double offset = candBearing - fireBearing;
                // Inline normalRelativeAngle to avoid method call overhead
                while (offset > Math.PI) offset -= 2 * Math.PI;
                while (offset < -Math.PI) offset += 2 * Math.PI;
                double gf = offset / mea;
                if (gf < -1.0) gf = -1.0;
                if (gf > 1.0) gf = 1.0;
                if (gf < minGF) minGF = gf;
                if (gf > maxGF) maxGF = gf;
            }
        }

        out[0] = surviving > 0 ? minDist : 0;
        out[1] = maxDist;
        out[2] = hasWave && surviving > 0 ? minGF : 0;
        out[3] = hasWave && surviving > 0 ? maxGF : 0;
        out[4] = surviving;
        out[5] = data.length / 2;
    }
}
