package cz.zamboch.autopilot.core.physics;

import cz.zamboch.autopilot.core.movement.CandidatePosition;

import java.util.Random;

/**
 * Pre-computed reachable positions at tick+10 from a given initial |velocity|.
 * Stores relative (dx, dy) offsets from the starting position at heading = 0.
 * At runtime: rotate by current heading, translate to current position,
 * clamp to walls, and optionally subsample with jitter to avoid
 * exploitable grid patterns.
 *
 * <p>Tables generated by {@link EnvelopeGenerator} on a 2px grid,
 * embedded in {@link EnvelopeData} as static final arrays (no I/O needed,
 * safe under Robocode's security sandbox).
 *
 * <p>Anti-discretization: candidates are jittered by ±1 px (half the
 * grid spacing) and randomly subsampled. The opponent never sees the
 * same set of evaluation points twice.
 */
public final class ReachableEnvelope {

    /** Horizon (ticks) for which the tables were generated. */
    public static final int HORIZON = 10;

    /** Grid spacing of the pre-computed positions (px). */
    static final int GRID = 2;

    /** Half-grid for random jitter (px). */
    private static final double JITTER = GRID / 2.0;

    /** Robot half-size for wall margin. */
    private static final int MARGIN = RobotPhysics.ROBOT_HALF_SIZE;

    private static final Random RNG = new Random();

    private ReachableEnvelope() {}

    /** Get the interleaved (dx,dy) byte array for the given absolute velocity. */
    private static byte[] getOffsets(int absVelocity) {
        return EnvelopeData.ALL[Math.min(8, Math.max(0, absVelocity))];
    }

    /**
     * Get all candidate positions reachable from the given state at tick+HORIZON.
     * Rotates pre-computed offsets by heading, translates to position,
     * discards positions outside battlefield walls. No jitter applied.
     *
     * @param current starting robot state
     * @param bfW battlefield width
     * @param bfH battlefield height
     * @return array of reachable candidate positions (may be large — ~2000)
     */
    public static CandidatePosition[] getAllCandidates(
            RobotState current, int bfW, int bfH) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);
        int numPoints = data.length / 2;

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        CandidatePosition[] buf = new CandidatePosition[numPoints];
        int n = 0;

        for (int i = 0; i < data.length; i += 2) {
            double dx = data[i];
            double dy = data[i + 1];
            double rx = dx * cosH + dy * sinH;
            double ry = -dx * sinH + dy * cosH;
            double x = current.x + rx;
            double y = current.y + ry;

            if (x < MARGIN || x > bfW - MARGIN
                    || y < MARGIN || y > bfH - MARGIN) {
                continue;
            }
            buf[n++] = new CandidatePosition(x, y, 0.0, HORIZON);
        }

        CandidatePosition[] result = new CandidatePosition[n];
        System.arraycopy(buf, 0, result, 0, n);
        return result;
    }

    /**
     * Get a random subsample of reachable candidates with ±1px jitter.
     * This is the primary online method — prevents exploitable grid patterns.
     *
     * @param current starting robot state
     * @param bfW battlefield width
     * @param bfH battlefield height
     * @param maxCandidates maximum number of candidates to return
     * @return subsampled, jittered candidate positions
     */
    public static CandidatePosition[] getCandidates(
            RobotState current, int bfW, int bfH, int maxCandidates) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        // Reservoir sampling with jitter
        CandidatePosition[] reservoir = new CandidatePosition[maxCandidates];
        int seen = 0;

        for (int i = 0; i < data.length; i += 2) {
            double dx = data[i] + (RNG.nextDouble() * 2 - 1) * JITTER;
            double dy = data[i + 1] + (RNG.nextDouble() * 2 - 1) * JITTER;
            double rx = dx * cosH + dy * sinH;
            double ry = -dx * sinH + dy * cosH;
            double x = current.x + rx;
            double y = current.y + ry;

            if (x < MARGIN || x > bfW - MARGIN
                    || y < MARGIN || y > bfH - MARGIN) {
                continue;
            }

            if (seen < maxCandidates) {
                reservoir[seen] = new CandidatePosition(x, y, 0.0, HORIZON);
            } else {
                int j = RNG.nextInt(seen + 1);
                if (j < maxCandidates) {
                    reservoir[j] = new CandidatePosition(x, y, 0.0, HORIZON);
                }
            }
            seen++;
        }

        int count = Math.min(seen, maxCandidates);
        CandidatePosition[] result = new CandidatePosition[count];
        System.arraycopy(reservoir, 0, result, 0, count);
        return result;
    }

    /**
     * Zero-allocation subsample: writes into a pre-allocated buffer with jitter.
     * The primary online method for per-tick path planning.
     *
     * @param current starting robot state
     * @param bfW battlefield width
     * @param bfH battlefield height
     * @param buf pre-allocated buffer (each element must be non-null)
     * @param maxCandidates max entries to write into buf
     * @return number of candidates written into buf[0..n-1]
     */
    public static int getCandidatesInto(
            RobotState current, int bfW, int bfH,
            CandidatePosition[] buf, int maxCandidates) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        // Reservoir sampling with jitter — writes into buf, zero allocation
        int seen = 0;

        for (int i = 0; i < data.length; i += 2) {
            double dx = data[i] + (RNG.nextDouble() * 2 - 1) * JITTER;
            double dy = data[i + 1] + (RNG.nextDouble() * 2 - 1) * JITTER;
            double rx = dx * cosH + dy * sinH;
            double ry = -dx * sinH + dy * cosH;
            double x = current.x + rx;
            double y = current.y + ry;

            if (x < MARGIN || x > bfW - MARGIN
                    || y < MARGIN || y > bfH - MARGIN) {
                continue;
            }

            if (seen < maxCandidates) {
                buf[seen].set(x, y, 0.0, HORIZON);
            } else {
                int j = RNG.nextInt(seen + 1);
                if (j < maxCandidates) {
                    buf[j].set(x, y, 0.0, HORIZON);
                }
            }
            seen++;
        }

        return Math.min(seen, maxCandidates);
    }

    /**
     * Count how many envelope positions survive wall clamping.
     * Used to compute ENVELOPE_FILL_RATIO feature.
     *
     * @return [surviving, total] positions
     */
    public static int[] countReachable(RobotState current, int bfW, int bfH) {
        int vi = (int) Math.round(Math.abs(current.velocity));
        byte[] data = getOffsets(vi);
        int numPoints = data.length / 2;

        double sinH = Math.sin(current.heading);
        double cosH = Math.cos(current.heading);

        int surviving = 0;
        for (int i = 0; i < data.length; i += 2) {
            double rx = data[i] * cosH + data[i + 1] * sinH;
            double ry = -data[i] * sinH + data[i + 1] * cosH;
            double x = current.x + rx;
            double y = current.y + ry;
            if (x >= MARGIN && x <= bfW - MARGIN
                    && y >= MARGIN && y <= bfH - MARGIN) {
                surviving++;
            }
        }
        return new int[]{surviving, numPoints};
    }
}
