"""Re-encode EnvelopeData.java from byte[] literals to a Base64 string.

Reads the existing Java file, parses the byte values out of each
`private static byte[] vN()` method, packs them into a single buffer with
a 2-byte big-endian length prefix per velocity, Base64-encodes the buffer,
and emits a new EnvelopeData.java in the same style as FirePowerData /
MovementData / FireTimingData / DefaultDataFile.

Run once from the workspace root with the project's Python venv:

    .\\intuition\\.venv\\Scripts\\python.exe scripts\\reencode_envelope_data.py
"""

from __future__ import annotations

import base64
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "core" / "src" / "main" / "java" / "cz" / "zamboch" / "autopilot" / "core" / "physics" / "EnvelopeData.java"


def parse_existing(path: Path) -> dict[int, bytes]:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"private static byte\[\] v(\d)\(\)\s*\{\s*return new byte\[\]\{(.*?)\}\s*;\s*\}",
        re.DOTALL,
    )
    chunks: dict[int, bytes] = {}
    for m in pattern.finditer(text):
        v = int(m.group(1))
        nums = [int(n) for n in re.findall(r"-?\d+", m.group(2))]
        if any(n < -128 or n > 127 for n in nums):
            raise ValueError(f"v{v}: value out of signed-byte range")
        chunks[v] = bytes((n + 256) % 256 for n in nums)
    if set(chunks.keys()) != set(range(9)):
        raise ValueError(f"expected v0..v8, got {sorted(chunks.keys())}")
    return chunks


def pack(chunks: dict[int, bytes]) -> bytes:
    buf = bytearray()
    for v in range(9):
        data = chunks[v]
        if len(data) > 0xFFFF:
            raise ValueError(f"v{v}: {len(data)} bytes does not fit in u16 length prefix")
        buf += struct.pack(">H", len(data))
        buf += data
    return bytes(buf)


def split_b64(b64: str, chunk_size: int = 60_000) -> list[str]:
    return [b64[i : i + chunk_size] for i in range(0, len(b64), chunk_size)]


def emit_java(parts: list[str], counts: dict[int, int], total_raw: int) -> str:
    summary = ", ".join(f"v{v}={counts[v]//2}" for v in range(9))
    lines: list[str] = []
    a = lines.append
    a("package cz.zamboch.autopilot.core.physics;")
    a("")
    a("/**")
    a(" * Auto-generated envelope tables. DO NOT EDIT.")
    a(" * Generated by {@link EnvelopeGenerator} with horizon=10, grid=2px.")
    a(" * Each entry is interleaved (dx, dy) signed-byte pairs relative to")
    a(" * heading=0 (north). Indexed by |velocity| 0..8.")
    a(" * Values fit in signed byte (-128..127); max offset is ~80px.")
    a(" *")
    a(f" * <p>Position counts: {summary}.")
    a(f" * Total raw payload: {total_raw} bytes.")
    a(" *")
    a(" * <p>Data is Base64-encoded and decoded once at class load. On-disk")
    a(" * format: for each velocity 0..8 a 2-byte big-endian length prefix is")
    a(" * followed by the raw signed bytes. The Base64 string is split into")
    a(" * chunks to stay under the JVM's 64\u00a0KB-per-string-constant limit.")
    a(" */")
    a("final class EnvelopeData {")
    a("    private EnvelopeData() {}")
    a("")
    for i, part in enumerate(parts):
        a(f'    private static final String D{i} = "{part}";')
    a("")
    a("    /** Decoded tables, indexed by |velocity| 0..8. */")
    a("    static final byte[][] ALL = decode();")
    a("")
    a("    private static byte[][] decode() {")
    total_b64 = sum(len(p) for p in parts)
    a(f"        StringBuilder sb = new StringBuilder({total_b64});")
    for i in range(len(parts)):
        a(f"        sb.append(D{i});")
    a("        byte[] raw = java.util.Base64.getDecoder().decode(sb.toString());")
    a("        byte[][] all = new byte[9][];")
    a("        int off = 0;")
    a("        for (int v = 0; v < 9; v++) {")
    a("            int n = ((raw[off] & 0xFF) << 8) | (raw[off + 1] & 0xFF);")
    a("            off += 2;")
    a("            byte[] data = new byte[n];")
    a("            System.arraycopy(raw, off, data, 0, n);")
    a("            off += n;")
    a("            all[v] = data;")
    a("        }")
    a("        return all;")
    a("    }")
    a("}")
    a("")
    return "\n".join(lines)


def main() -> None:
    chunks = parse_existing(SRC)
    counts = {v: len(b) for v, b in chunks.items()}
    raw = pack(chunks)
    b64 = base64.b64encode(raw).decode("ascii")
    parts = split_b64(b64)
    java_src = emit_java(parts, counts, len(raw))
    SRC.write_text(java_src, encoding="utf-8")
    print(f"raw bytes: {len(raw)}")
    print(f"base64 chars: {len(b64)} in {len(parts)} string(s)")
    print(f"counts (positions per velocity): {[counts[v] // 2 for v in range(9)]}")
    print(f"wrote {SRC}")


if __name__ == "__main__":
    main()
